### ISSUE TITLE
apostrophes in NAICS data showing up as â€™

### ISSUE THREAD

**Issue by louh** [codeforamerica/naics-api#11]
See the title for http://naics-api.herokuapp.com/v0/q?year=2012&code=315240

**Comment by ycombinator** [comment]
This is because smart quotes are being used in those places in the raw data. See https://github.com/louh/naics-api/blob/master/data/naics-2012.json#L410-L413. My suggestion would be to replace the smart quotes with regular quotes when this data is ingested so that all downstream consumers (such as the API) benefit.

**Comment by louh** [comment]
Thanks. Generally I need to either automate the conversion process better or write down all the steps somewhere...
